#!/usr/bin/env bash
# Run Nginx as Nginx

service nginx stop
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user.*/user nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
